E_commerce_application/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path( '', include( 'home_module.urls', namespace='home_module' ) ),
    path( 'products/', include( 'product_module.urls', namespace='product_module' ) ),
    path( 'order/', include( 'order_module.urls', namespace='order_module' ) ),
    path( 'accounts/', include( 'account_module.urls', namespace='account_module' ) ),
    path( 'contact-us/', include( 'contact_module.urls', namespace='contact_module' ) ),
    path( 'admin/', admin.site.urls ),
]

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

account_module/urls.py
from django.urls import path
from account_module import views

app_name = 'account_module'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('user-account/', views.UserAccountView.as_view(), name='user-account'),
    path('edit-account/', views.edit_user_info, name='edit-account'),
    path('active-account/<active_code>', views.activation_account_view, name='active_account'),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password/<active_code>/', views.reset_password_view, name='reset_password'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home_module'

urlpatterns = [
    path( '', views.HomeView.as_view(), name='home-view' )
]

order_module/urls.py
from django.urls import path
from . import views

app_name = 'order_module'

urlpatterns = [
    path('add-user-order/', views.add_user_order, name='add-new-order'),
    path('add-coupon-code/', views.add_coupon_code, name='add-coupon-code'),
    path('user-orders/', views.user_orders_view, name='user-orders'),
    path('order-detail/<order_id>', views.user_order_detail, name='order-detail'),
    path('complete-order/', views.complete_order, name='complete-order'),
    path('user-open-order/', views.UserOpenOrder.as_view(), name='user-open-order'),
    path('change_item_counter', views.change_item_count, name='change_item_counter'),
    path('ajax/load-cities/', views.get_cities, name='load_cities'),
    path('export-pdf/<int:order_id>/', views.export_pdf_order, name='export-pdf-order')
]

account_module/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

gender_choices = (
    ('Male', 'Male'),
    ('Female', 'Female')
)


class User(AbstractUser):
    phone_number = models.CharField(max_length=20)
    avatar = models.ImageField(upload_to='user_image/', null=True)
    gender = models.CharField(("gender"), choices=gender_choices, max_length=10)
    active_code = models.CharField(max_length=100, null=True)
    numeral_active_code = models.CharField(max_length=6, null=True)

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users profile'

    def __str__(self):
        return self.email

account_module/forms.py
from django import forms
from .models import User


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class EditUserAccountModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'avatar')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'})
        }


gender_choices = (
    ('Male', 'Male'),
    ('Female', 'Female')
)


class RegisterForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    gender = forms.CharField(widget=forms.Select(choices=gender_choices))
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    avatar = forms.ImageField(required=False)

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password == confirm_password:
            return confirm_password
        raise forms.ValidationError('password and it\'s repetition must be matched!')


class ActivationCodeForm(forms.Form):
    active_code = forms.CharField(label='active code', widget=forms.TextInput(attrs={'class': 'form-control'}))


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))


class ResetPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                                       label='current password')
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='new password')
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='confirm new password')

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get('new_password')
        confirm_new_password = self.cleaned_data.get('confirm_new_password')
        if new_password == confirm_new_password:
            return confirm_new_password
        raise forms.ValidationError('new password and it\'s confirmation are not equal')

account_module/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from utils.email_services import EmailService
from account_module.models import User
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import (
    LoginForm,
    EditUserAccountModelForm,
    RegisterForm,
    ResetPasswordForm,
    ForgotPasswordForm,
    ActivationCodeForm,
    ChangePasswordForm
)
from django.contrib.auth.mixins import LoginRequiredMixin
import random


def generate_integer_active_code(length=6):
    numeral_active_code = ''
    for _ in range(length):
        numeral_active_code += str(random.randint(1, 9))
    return numeral_active_code


#  login user
def login_view(request):
    if request.user.is_authenticated:
        return redirect('home_module:home-view')
    login_form = LoginForm(request.POST or None)
    context = {
        'title': 'login',
        'login_form': login_form
    }
    if request.method == 'POST':
        if login_form.is_valid():
            email = login_form.cleaned_data.get('email')
            password = login_form.cleaned_data.get('password')
            user = User.objects.filter(username=email).first()
            if user is not None:
                if user.is_active:
                    is_correct = user.check_password(password)
                    if is_correct:
                        login(request, user)
                        return redirect(reverse('account_module:user-account'))
                    else:
                        login_form.add_error('email', 'email or password is incorrect')
                login_form.add_error('email', 'your account must be active first!')
            login_form.add_error('email', 'email or password is incorrect')
    context = {'title': 'login', 'login_form': login_form}
    return render(request, 'account_module/login_page.html', context)


@login_required(login_url='account_module:login')
def logout_user(request):
    logout(request)
    return redirect('account_module:login')


class RegisterView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home_module:home-view')
        register_form = RegisterForm()
        context = {
            'register_form': register_form,
            'title': 'register view'
        }
        return render(request, 'account_module/register_page.html', context)

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('home_module:home-view')
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            email = register_form.cleaned_data.get('email')
            password = register_form.cleaned_data.get('password')
            gender = register_form.cleaned_data.get('gender')
            user_exist = User.objects.filter(email=email).exists()
            if user_exist:
                register_form.add_error('email', 'email is not valid!')
            else:
                string_active_code = get_random_string(72)
                numeral_active_code = generate_integer_active_code()
                new_user = User(email=email, password=password, gender=gender, username=email, is_active=False,
                                active_code=string_active_code, numeral_active_code=numeral_active_code)
                new_user.set_password(password)
                new_user.save()
                EmailService.send_email('account activation', new_user.email, {'user': new_user},
                                        'emails/active_account.html')

                return render(request, 'emails/check_email.html', {'user': new_user})
                # return redirect(reverse('account_module:login'))
        context = {
            'register_form': register_form
        }
        return render(request, 'account_module/register_page.html', context)


class UserAccountView(LoginRequiredMixin, View):
    def get(self, request):
        context = {
            'title': 'user Account'
        }
        return render(request, 'account_module/user_account.html', context)


@login_required(login_url='account_module:login')
def edit_user_info(request):
    current_user = User.objects.filter(id=request.user.id).first()
    if request.method == 'POST':
        edit_form = EditUserAccountModelForm(request.POST, request.FILES, instance=current_user)
        if edit_form.is_valid():
            edit_form.save(commit=True)
            return redirect('account_module:user-account')
    else:
        edit_form = EditUserAccountModelForm(instance=current_user)
    context = {
        'title': 'user form',
        'edit_form': edit_form,
        'user': current_user
    }
    return render(request, 'account_module/user_edit_form.html', context)


def activation_account_view(request, active_code):
    user = User.objects.filter(active_code__iexact=active_code).first()
    active_form = ActivationCodeForm(request.POST or None)
    if user is not None:
        if not user.is_active:
            if request.method == 'POST':
                if active_form.is_valid():
                    user_active_code = active_form.cleaned_data.get('active_code')
                    if user.numeral_active_code == user_active_code:
                        user.is_active = True
                        user.active_code = get_random_string(72)
                        user.numeral_active_code = generate_integer_active_code()
                        user.save()
                        return redirect(reverse('account_module:login'))
                    else:
                        active_form.add_error('active_code', 'activation code is wrong')
            else:
                context = {
                    'form': active_form,
                    'title': 'account activation'
                }
                return render(request, 'account_module/active_account_page.html', context)
    raise Http404


class ForgotPasswordView(View):
    def get(self, request):
        forgot_pass_form = ForgotPasswordForm()
        context = {'form': forgot_pass_form, 'title': 'forgot password'}
        return render(request, 'account_module/forgot_password.html', context)

    def post(self, request):
        forgot_pass_form = ForgotPasswordForm(request.POST)
        if forgot_pass_form.is_valid():
            user_email = forgot_pass_form.cleaned_data.get('email')
            user: User = User.objects.filter(email=user_email).first()
            if user is not None:
                EmailService.send_email(subject='forgot password', to=user.email, context={'user': user},
                                        template_name='emails/forgot_password_email.html')
            return redirect(reverse('account_module:login'))
        context = {'form': forgot_pass_form, 'title': 'forgot password'}
        return render(request, 'account_module/forgot_password.html', context)


def reset_password_view(request, active_code):
    user = User.objects.filter(active_code__iexact=active_code).first()
    if user is not None:
        reset_pass_form = ResetPasswordForm(request.POST or None)
        if reset_pass_form.is_valid():
            user_pass = reset_pass_form.cleaned_data.get('password')
            user.set_password(user_pass)
            user.active_code = get_random_string(72)
            user.save()
            return redirect(reverse('account_module:login'))
        context = {'form': reset_pass_form, 'title': 'retrieve password'}
        return render(request, 'account_module/reset_password.html', context)


class ChangePasswordView(View):
    def get(self, request):
        context = {
            'form': ChangePasswordForm(),
            'title': 'change password'
        }
        return render(request, 'account_module/change_password_page.html', context)

    def post(self, request):
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            user: User = User.objects.filter(id=request.user.id).first()
            if user.check_password(form.cleaned_data.get('current_password')):
                user.set_password(form.cleaned_data.get('new_password'))
                user.save()
                logout(request)
                return redirect(reverse('account_module:login'))
            else:
                form.add_error('current_password', 'your password is wrong')
        context = {
            'form': form,
            'title': 'change password'
        }
        return render(request, 'account_module/change_password_page.html', context)

account_module/templates/account_module/active_account_page.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="col-md-3 col-offset-5">
        <h2 class="text-center text-danger">Activation Form</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.active_code.label_tag }}
            {{ form.active_code }}
            {{ form.active_code.errors }}
            <button type="submit" class="btn-success mt-2">Send</button>
        </form>
    </div>
{% endblock %}

account_module/templates/account_module/change_password_page.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <h5 class="text-center text-primary">Change Your Password</h5>
    <div class="container">
        <form method="post" action="{% url 'account_module:change_password' %}">
            {% csrf_token %}
            <div class="row m-2">
                <div class="col">
                    {{ form.as_p }}
                </div>
            </div>
            <div class="text-right">
                <button type="submit" class="btn btn-primary mt-2 mr-3">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}

account_module/templates/account_module/forgot_password.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

    <div class="container">
        <h2 class="text-center text-warning mt-3">Forgot Password</h2>
        <div class="col-md-6 mb-5" id="div-form">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-block mt-3" id="btn-login">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

account_module/templates/account_module/login_page.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

    <div class="container">
        <h2 class="text-center text-warning mt-3">Login Form</h2>
        <div class="col-md-6 mb-5"  id="div-form">
            <form method="post">
                {% csrf_token %}
                {{ login_form.as_p }}
                <button type="submit" class="btn btn-block mt-3" id="btn-login">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

account_module/templates/account_module/register_page.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center text-warning mt-3">Register Form</h2>
        <div class="col-md-6 mb-5" id="div-form">
            <form method="post">
                {% csrf_token %}
                {#                {{ register_form.as_p }}#}
                {% for field in register_form %}
                    <div class="register-div">
                        <label>{{ field.label_tag }}</label>
                        {{ field }}
                    </div>
                    {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <button type="submit" class="btn btn-block mt-3" id="btn-login">Sign Up</button>
            </form>
        </div>
    </div>
{% endblock %}

account_module/templates/account_module/reset_password.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}

    <div class="container">
        <h2 class="text-center text-warning mt-3">Login Form</h2>
        <div class="col-md-6 mb-5" id="div-form">
            <form method="post">
                {% csrf_token %}
                {% for fiels in form %}
                    {{ fiels.label_tag }}
                    {{ fiels }}
                {% endfor %}
                <button type="submit" class="btn btn-block mt-3" id="btn-login">Reset</button>
            </form>
        </div>
    </div>
{% endblock %}

account_module/templates/account_module/user_account.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="container p-3 m-3">
        <div class="col-md-3">
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'account_module:edit-account' %}">Edit Account</a></li>
                <li class="list-group-item"><a href="{% url 'account_module:change_password' %}">Change Password</a></li>
                <li class="list-group-item"><a href="{% url 'order_module:user-orders' %}">Your Orders</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

account_module/templates/account_module/user_edit_form.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <h5 class="text-center text-primary">Edit You Information</h5>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if  user.avatar %}
                <img src="{{ user.avatar.url }}"/>
{#                <div class="col">#}
{#                    {{ edit_form.avatar.label_tag }}#}
{#                    {{ edit_form.avatar }}#}
{#                </div>#}
            {% endif %}
            <div class="row m-2">
                <div class="col">
                    {{ edit_form.avatar.label_tag }}
                    {{ edit_form.avatar }}
                </div>
                <div class="col">
                    {{ edit_form.username.label_tag }}
                    {{ edit_form.username }}
                </div>
                <div class="col">
                    {{ edit_form.email.label_tag }}
                    {{ edit_form.email }}
                </div>
            </div>
            <div class="row m-2">
                <div class="col">
                    {{ edit_form.first_name.label_tag }}
                    {{ edit_form.first_name }}
                </div>
                <div class="col">
                    {{ edit_form.last_name.label_tag }}
                    {{ edit_form.last_name }}
                </div>
            </div>
            <div class="text-right">
                <button type="submit" class="btn btn-primary mt-2 mr-3">Submit</button>
            </div>
        </form>
    </div>
{% endblock %}