E_commerce_application/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path( '', include( 'home_module.urls', namespace='home_module' ) ),
    path( 'products/', include( 'product_module.urls', namespace='product_module' ) ),
    path( 'order/', include( 'order_module.urls', namespace='order_module' ) ),
    path( 'accounts/', include( 'account_module.urls', namespace='account_module' ) ),
    path( 'contact-us/', include( 'contact_module.urls', namespace='contact_module' ) ),
    path( 'admin/', admin.site.urls ),
]

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home_module'

urlpatterns = [
    path( '', views.HomeView.as_view(), name='home-view' )
]

order_module/urls.py
from django.urls import path
from . import views

app_name = 'order_module'

urlpatterns = [
    path('add-user-order/', views.add_user_order, name='add-new-order'),
    path('add-coupon-code/', views.add_coupon_code, name='add-coupon-code'),
    path('user-orders/', views.user_orders_view, name='user-orders'),
    path('order-detail/<order_id>', views.user_order_detail, name='order-detail'),
    path('complete-order/', views.complete_order, name='complete-order'),
    path('user-open-order/', views.UserOpenOrder.as_view(), name='user-open-order'),
    path('change_item_counter', views.change_item_count, name='change_item_counter'),
    path('ajax/load-cities/', views.get_cities, name='load_cities'),
    path('export-pdf/<int:order_id>/', views.export_pdf_order, name='export-pdf-order')
]

order_module/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from product_module.models import Product, ProductDetail


class Order(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_paid = models.BooleanField(default=False, help_text='order paid or not')
    is_send = models.BooleanField(default=False, help_text='order sent or not')
    created_date = models.DateTimeField(help_text='created current user order', auto_now_add=True)
    payment_date = models.DateTimeField(null=True, blank=True, help_text='order payment date')
    tracking_code = models.CharField(null=True, max_length=50)
    coupon_code = models.ForeignKey('Coupon', null=True, on_delete=models.DO_NOTHING, blank=True)

    # complete order
    name = models.CharField(max_length=50, null=True, blank=True)
    family = models.CharField(max_length=50, null=True, blank=True)
    post_code = models.IntegerField(null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    province = models.ForeignKey('Province', on_delete=models.CASCADE, null=True, blank=True)
    city = models.ForeignKey('City', on_delete=models.CASCADE, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def get_total_price(self):
        amount = 0
        # detail is closed(payed)
        if self.is_paid:
            for detail in self.orderdetail_set.all():
                amount += detail.final_price * detail.count
            if self.coupon_code is not None:
                amount -= (amount * self.coupon_code.amount) / 100
        # detail is open(not payed)
        else:
            for detail in self.orderdetail_set.all():
                amount += detail.product_detail.price * detail.count
            if self.coupon_code is not None:
                amount -= (amount * self.coupon_code.amount) / 100
        return amount

    class Meta:
        verbose_name = 'user order'
        verbose_name_plural = 'orders list'

    def __str__(self):
        return self.owner


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_detail = models.ForeignKey(ProductDetail, on_delete=models.CASCADE)
    final_price = models.IntegerField(null=True, help_text='the price will fix after payment', blank=True)
    count = models.IntegerField(null=True)

    class Meta:
        verbose_name = 'order detail'
        verbose_name_plural = 'order detail lists'

    def __str__(self):
        return f'{self.product}'


class Province(models.Model):
    province_name = models.CharField(max_length=30)

    def __str__(self):
        return self.province_name

    class Meta:
        verbose_name = 'province'
        verbose_name_plural = 'provinces'


class City(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    city_name = models.CharField(max_length=30)

    def __str__(self):
        return self.city_name

    class Meta:
        verbose_name = 'city'
        verbose_name_plural = 'cities'


class Coupon(models.Model):
    code = models.CharField(max_length=10)
    amount = models.IntegerField()

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'discount code'
        verbose_name_plural = 'coupon codes'

order_module/forms.py
from django import forms
from .models import Province, City, Order


class CompleteForm( forms.ModelForm ):
    class Meta:
        model = Order
        fields = (
            'name',
            'family',
            'phone_number',
            'post_code',
            'province',
            'city',
            'address',
            'description'
        )
        exclude = (
            'owner',
            'is_paid',
            'is_send',
            'created_date',
            'payment_date',
            'tracking_code',
            'coupon_code'
        )

        widgets = {
            'name': forms.TextInput( attrs={'class': 'form-control mb-3'} ),
            'family': forms.TextInput( attrs={'class': 'form-control mb-3'} ),
            'post_code': forms.NumberInput( attrs={'class': 'form-control mb-3'} ),
            'phone_number': forms.NumberInput( attrs={'class': 'form-control mb-3'} ),
            'province': forms.Select( attrs={'class': 'form-control mb-3', 'id': 'province'} ),
            'city': forms.Select( attrs={'class': 'form-control mb-3', 'id': 'city'} ),
            'address': forms.Textarea( attrs={'class': 'form-control mb-3', 'row': '3'} ),
            'description': forms.Textarea( attrs={'class': 'form-control mb-3', 'row': '3'} )

        }

    def __init__(self, *args, **kwargs):
        super().__init__( *args, **kwargs )
        self.fields['city'].queryset = City.objects.none()
        self.fields['description'].required = False

        if 'province' in self.data:
            try:
                province_id = int( self.data.get( 'province' ) )
                self.fields['city'].queryset = City.objects.filter( province_id=province_id ).order_by(
                    'city_name' )
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset

        # elif self.instance.pk:
        #     self.fields['city'].queryset = self.instance.province.city_set.order_by( 'city_name' )

order_module/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import get_template, render_to_string
from django.views.generic import ListView, DetailView
from .models import Order, OrderDetail, Coupon, City
from product_module.models import Product
from django.http import JsonResponse, HttpResponse
from .forms import CompleteForm
import random
import string


def create_tracking_code():
    # create tracking code
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


@login_required
def add_user_order(request):
    if request.method == 'GET':
        return redirect('home_module:home-view')
    order_form_data = request.POST  # get form info (POST request)
    # get product order details
    product: Product = Product.objects.filter(id=order_form_data['product']).first()
    product_detail = product.productdetail_set.filter(color=order_form_data['product-color']).first()
    # find or create an open order
    order: Order = Order.objects.filter(owner=request.user, is_paid=False).first()
    if order is None:
        tracking_code = create_tracking_code()
        order: Order = Order.objects.create(owner=request.user,
                                            tracking_code=tracking_code)
    order_detail: OrderDetail = order.orderdetail_set.filter(product=product, product_detail=product_detail).first()
    if order_detail is None:
        order_detail = order.orderdetail_set.create(product=product, product_detail=product_detail,
                                                    count=order_form_data['quantity'])
    else:
        order_detail.count += int(order_form_data['quantity'])

    if product_detail.discount_price:
        order_detail.price = product_detail.discount_price
    else:
        order_detail.price = product_detail.price
    product_detail.quantity -= int(order_form_data['quantity'])
    product_detail.save()
    order_detail.save()
    return redirect('order_module:user-open-order')


class UserOpenOrder(DetailView, LoginRequiredMixin):
    model = Order
    template_name = 'order_module/user_open_order_list.html'
    context_object_name = 'order'

    def get_object(self, queryset=None):
        open_order = Order.objects.filter(owner=self.request.user, is_paid=False).first()
        return open_order

    def get_context_data(self, **kwargs):
        context = super(UserOpenOrder, self).get_context_data()
        context['title'] = f'{self.request.user.username} open order'
        return context


@login_required
def change_item_count(request):
    print(request)
    '''
           delete, decrease or increase counter of an order detail
    '''
    detail_id = request.GET.get('detail_id')
    state = request.GET.get('state')
    if detail_id is None or state is None:
        return JsonResponse({'status': 'detail_or_state_not_found', 'icon': 'warning'})
    detail: OrderDetail = OrderDetail.objects.filter(id=detail_id, order__is_paid=False,
                                                     order__owner_id=request.user.id).first()
    if detail is None:
        return JsonResponse({'status': 'detail_found', 'icon': 'warning'})
    if state == 'increase':
        if detail.product_detail.quantity > 0:
            detail.count += 1
            detail.save()
            detail.product_detail.quantity -= 1
            detail.product_detail.save()
        else:
            return JsonResponse({'status': 'the required number is not available', 'icon': 'warning'})
    elif state == 'decrease':
        if detail.count == 1:
            detail.delete()
        else:
            detail.count -= 1
            detail.save()
            detail.product_detail.quantity += 1
            detail.product_detail.save()
    elif state == 'all':
        detail.product_detail.quantity += detail.count
        detail.product_detail.save()
        detail.delete()
    else:
        return JsonResponse({'status': 'invalid_state', 'icon': 'error'})
    return JsonResponse({'success': 'successful',
                         'icon': 'success',
                         'body': render_to_string(
                             template_name='order_module/includes/open_order_detail_component.html',
                             context={'order': Order.objects.filter(owner_id=request.user.id, is_paid=False).first()})
                         })


@login_required
def add_coupon_code(request):
    open_order: Order = Order.objects.filter(owner=request.user, is_paid=False).first()
    if open_order is not None:
        if open_order.coupon_code is None:
            coupon_form = request.POST['coupon']
            coupon = Coupon.objects.filter(code=coupon_form).first()
            if coupon is not None:
                open_order.coupon_code = coupon
                open_order.save()
                context = {'message': 'coupon code added successfully!', 'total': open_order.get_total_price()}
            else:
                context = {'message': 'coupon code not found!'}
        else:
            context = {'message': 'you used coupon code before!'}
    else:
        context = {'message': 'something went wrong!'}
    return JsonResponse(context)


def get_cities(request, ):
    cities = City.objects.filter(province_id=request.GET.get('province'))
    context = {'cities': cities}
    return render(request, 'order_module/cities_dropdown.html', context)


@login_required
def complete_order(request):
    open_order: Order = Order.objects.get(owner=request.user, is_paid=False)
    if open_order is None:
        return redirect('home_module:home-view')
    context = {
        'title': 'complete order'
    }
    complete_form = CompleteForm(request.POST or None, instance=open_order)
    if request.method == 'POST':
        if complete_form.is_valid():
            open_order.name = complete_form.cleaned_data.get('name')
            open_order.family = complete_form.cleaned_data.get('family')
            open_order.post_code = complete_form.cleaned_data.get('post_code')
            open_order.phone_number = complete_form.cleaned_data.get('phone_number')
            open_order.province = complete_form.cleaned_data.get('province')
            open_order.city = complete_form.cleaned_data.get('city')
            open_order.address = complete_form.cleaned_data.get('address')
            open_order.description = complete_form.cleaned_data.get('description')
            open_order.save()
            return redirect('order_module:order-detail', open_order.id)
    context['complete_form'] = complete_form
    return render(request, 'order_module/complete_order.html', context)


@login_required(login_url='account_module:login')
def user_orders_view(request):
    user_orders = Order.objects.filter(owner=request.user)
    context = {
        'title': 'user orders',
        'orders': user_orders
    }
    return render(request, 'order_module/user_orders.html', context)


@login_required(login_url='account_module:login')
def user_order_detail(request, order_id):
    order = Order.objects.filter(id=order_id).first()
    context = {'title': 'order detail', 'order': order}
    return render(request, 'order_module/order_detail.html', context)


# export an order as a pdf
def export_pdf_order(request, order_id):
    response = HttpResponse(content_type='appllication/pdf')
    order = Order.objects.filter(id=order_id).first()
    response['content-Disposiotion'] = 'filename=order' + '.pdf'
    template_path = 'order_module/html_to_pdf_order.html'
    template = get_template(template_path)
    context = {'order': order}
    html = template.render(context)
    pisa.CreatePDF(html, dest=response)
    return response

order_module/templates/order_module/cities_dropdown.html
<option value="">---------</option>
{% for city in cities %}
    <option value="{{ city.pk }}">{{ city.city_name }}</option>
{% endfor %}

order_module/templates/order_module/complete_order.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="container">
        <h4 class="text-center text-warning m-4 p-2">Complete Form</h4>
        <form method="post" data-cities-url="{% url 'order_module:load_cities' %}" id="completeForm" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.name.label }}:</label>
                    {{ complete_form.name }}
                </div>
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.family.label }}:</label>
                    {{ complete_form.family }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.post_code.label }}:</label>
                    {{ complete_form.post_code }}
                </div>
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.phone_number.label }}:</label>
                    {{ complete_form.phone_number }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.province.label }}:</label>
                    {{ complete_form.province }}
                </div>
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.city.label }}:</label>
                    {{ complete_form.city }}
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.address.label }}:</label>
                    {{ complete_form.address }}
                </div>
                <div class="col-lg-6 col-md-6 form-group">
                    <label>{{ complete_form.description.label }}:</label>
                    {{ complete_form.description }}
                </div>
            </div>
            <button class="btn btn-warning btn-block" type="submit">Checkout</button>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#province").change(function () {
            var url = $("#completeForm").attr("data-cities-url");
            var provinceId = $(this).val();
            console.log(provinceId)
            $.ajax({
                url: url,
                data: {
                    'province': provinceId
                },
                success: function (data) {
                    $("#city").html(data);
                }
            });
        });
    </script>
{% endblock %}

order_module/templates/order_module/html_to_pdf_order.html
{% extends 'shared/layout.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <h5 class="text-center m-2 p-2 text-primary"> Your Order Detail</h5>
    <div class="container">
        <table class="table">
            <thead>
            <tr class="text-center table-warning">
                <th scope="col">Order</th>
                <th scope="col">FullName</th>
                <th scope="col">Price</th>
                <th scope="col">Is Paid</th>
                <th scope="col">Is Send</th>
            </tr>
            </thead>
            <tbody>
            <tr class="text-center table">
                <th>{{ order.tracking_code }}</th>
                <td>{{ order.name }} {{ order.family }}</td>
                <td>{{ order.get_total_price }}</td>
                <td>{% if order.is_paid %} Paid {% else %} Not Yet {% endif %}</td>
                <td>{% if order.is_send %} Sent {% else %} Not Yet {% endif %}</td>
            </tr>
            </tbody>
        </table>
        <hr>
        <table class="table">
            <tr class="text-center table-active">
                <th scope="col">Address</th>
                <th scope="col">Phone</th>
                <th scope="col">Post Code</th>
                <th scope="col">City</th>
                <th scope="col">Province</th>
            </tr>
            <tr class="text-center">
                <th scope="col">{{ order.address }}</th>
                <th scope="col">{{ order.phone_number }}</th>
                <th scope="col">{{ order.post_code }}</th>
                <th scope="col">{{ order.city }}</th>
                <th scope="col">{{ order.province }}</th>
            </tr>
        </table>
        <hr>
        <table class="table">
            <thead>
            <tr class="text-center table-info">
                <th scope="col">#</th>
                <th scope="col">product</th>
                <th scope="col">Color</th>
                <th scope="col">Count</th>
                <th scope="col">Price</th>
                <th scope="col">Total Price</th>
            </tr>
            </thead>
            <tbody>
            {% for detail in order.orderdetail_set.all %}
                <tr class="text-center">
                    <th>{{ forloop.counter }}</th>
                    <th>{{ detail.product }}</th>
                    <td>{{ detail.product_detail.color }}</td>
                    <td>{{ detail.count }}</td>
                    <td class="text-danger">
                        {% if detail.product_detail.discount_price %}
                            <del>{{ detail.product_detail.price }} $</del>
                            {{ detail.product_detail.discount_price }} $
                        {% else %}
                            {{ detail.product_detail.price }} $
                        {% endif %}
                    </td>
                    <td class="text-danger">
                        {% if detail.product_detail.discount_price %}
                            {% widthratio detail.product_detail.discount_price 1 detail.count %}
                        {% else %}
                            {% widthratio detail.product_detail.price 1 detail.count %}
                        {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {#        <a class="btn btn-success" href="{% url 'order_module:export-pdf-order' order.id %}">Export PDF</a>#}
    </div>
{% endblock %}

order_module/templates/order_module/order_detail.html
{% extends 'shared/layout.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <h5 class="text-center m-2 p-2 text-primary"> Your Order Detail</h5>
    <div class="container">
        <table class="table">
            <thead>
            <tr class="text-center table-warning">
                <th scope="col">Order</th>
                <th scope="col">FullName</th>
                <th scope="col">Price</th>
                <th scope="col">Is Paid</th>
                <th scope="col">Is Send</th>
            </tr>
            </thead>
            <tbody>
            <tr class="text-center table">
                <th>{{ order.tracking_code }}</th>
                <td>{{ order.name }} {{ order.family }}</td>
                <td>{{ order.get_total_price }}</td>
                <td>{% if order.is_paid %} Paid {% else %} Not Yet {% endif %}</td>
                <td>{% if order.is_send %} Sent {% else %} Not Yet {% endif %}</td>
            </tr>
            </tbody>
        </table>
        <hr>
        <table class="table">
            <tr class="text-center table-active">
                <th scope="col">Address</th>
                <th scope="col">Phone</th>
                <th scope="col">Post Code</th>
                <th scope="col">City</th>
                <th scope="col">Province</th>
                {% if not order.is_paid %}
                    <th>Edit</th>
                {% endif %}
            </tr>
            <tr class="text-center">
                <th scope="col">{{ order.address }}</th>
                <th scope="col">{{ order.phone_number }}</th>
                <th scope="col">{{ order.post_code }}</th>
                <th scope="col">{{ order.city }}</th>
                <th scope="col">{{ order.province }}</th>
                {% if not order.is_paid %}
                    <th><a href="{% url 'order_module:complete-order' %}" class="btn btn-warning">Edit</a></th>
                {% endif %}
            </tr>
        </table>
        <hr>
        <table class="table">
            <thead>
            <tr class="text-center table-info">
                <th scope="col">#</th>
                <th scope="col">product</th>
                <th scope="col">Color</th>
                <th scope="col">Count</th>
                <th scope="col">Price</th>
                <th scope="col">Total Price</th>
            </tr>
            </thead>
            <tbody>
            {% for detail in order.orderdetail_set.all %}
                <tr class="text-center">
                    <th>{{ forloop.counter }}</th>
                    <th>{{ detail.product }}</th>
                    <td>{{ detail.product_detail.color }}</td>
                    <td>{{ detail.count }}</td>
                    <td class="text-danger">
                        {% if detail.product_detail.discount_price %}
                            <del>{{ detail.product_detail.price }} $</del>
                            {{ detail.product_detail.discount_price }} $
                        {% else %}
                            {{ detail.product_detail.price }} $
                        {% endif %}
                    </td>
                    <td class="text-danger">
                        {% if detail.product_detail.discount_price %}
                            {% widthratio detail.product_detail.discount_price 1 detail.count %}
                        {% else %}
                            {% widthratio detail.product_detail.price 1 detail.count %}
                        {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

order_module/templates/order_module/user_open_order_list.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% if object %}
        <div id="open-order-content">
            {% include 'order_module/includes/open_order_detail_component.html' %}
        </div>
    {% else %}
        <p class="text-center text-danger m-5">you did not order any thing</p>
    {% endif %}
    <!-- JS -->
{% endblock %}

order_module/templates/order_module/user_orders.html
{% extends 'shared/layout.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div class="p-3 m-5">
        {% if orders %}
            <table class="table table-striped">
                <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">Order</th>
                    <th scope="col">Price</th>
                    <th scope="col">Paid/unPaid</th>
                    <th scope="col">Send/unSend</th>
                    <th scope="col">Detail</th>
                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                    <tr class="text-center">
                        <th scope="row" class="text-danger">{{ forloop.counter }}</th>
                        <td class="text-secondary">{{ order.owner }}</td>
                        <td class="text-success">{{ order.get_total_price }}</td>
                        <td class="text-danger">
                            {% if order.is_paid %}
                                Paid
                            {% else %}
                                Not Paid
                            {% endif %}
                        </td>
                        <td class="text-danger">
                            {% if order.is_send %}
                                Sent
                            {% else %}
                                Not Send
                            {% endif %}
                        </td>
                        <td><a class="btn btn-primary text-light" href="{% url 'order_module:order-detail' order.id %}">Detail</a>
                        </td>
                    </tr>
                {% empty %}
                    <h3>you dont have any order</h3>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h3 class="text-center text-primary">you dont have any order</h3>
        {% endif %}
    </div>
{% endblock %}