E_commerce_application/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path( '', include( 'home_module.urls', namespace='home_module' ) ),
    path( 'products/', include( 'product_module.urls', namespace='product_module' ) ),
    path( 'order/', include( 'order_module.urls', namespace='order_module' ) ),
    path( 'accounts/', include( 'account_module.urls', namespace='account_module' ) ),
    path( 'contact-us/', include( 'contact_module.urls', namespace='contact_module' ) ),
    path( 'admin/', admin.site.urls ),
]

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home_module'

urlpatterns = [
    path( '', views.HomeView.as_view(), name='home-view' )
]

order_module/urls.py
from django.urls import path
from . import views

app_name = 'order_module'

urlpatterns = [
    path('add-user-order/', views.add_user_order, name='add-new-order'),
    path('add-coupon-code/', views.add_coupon_code, name='add-coupon-code'),
    path('user-orders/', views.user_orders_view, name='user-orders'),
    path('order-detail/<order_id>', views.user_order_detail, name='order-detail'),
    path('complete-order/', views.complete_order, name='complete-order'),
    path('user-open-order/', views.UserOpenOrder.as_view(), name='user-open-order'),
    path('change_item_counter', views.change_item_count, name='change_item_counter'),
    path('ajax/load-cities/', views.get_cities, name='load_cities'),
    path('export-pdf/<int:order_id>/', views.export_pdf_order, name='export-pdf-order')
]

product_module/urls.py
from django.urls import path
from . import views

app_name = 'product_module'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('new-products/', views.NewProductListView.as_view(), name='new-product-list'),
    path('product-brand/<brand_name>/', views.ProductByBrand.as_view(), name='product-list-by-brand'),
    path('product-category/<category_name>/', views.ProductByCategory.as_view(), name='product-list-by-category'),
    path('product-ajax-price/', views.get_product_detail, name='product-detail-price'),
    path('search/', views.product_list_by_search, name='search-products-list'),
    path('ajax_filtering/', views.get_json_filtering, name='ajax_filtering')
]

product_module/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.db.models import Q


class ProductManager(models.Manager):
    def get_product_by_filter(self, category_name=None, brand_name=None):
        lookup = Q(category__title=category_name) | Q(brand__title=brand_name)
        return self.get_queryset().filter(lookup).distinct()


class Brand(models.Model):
    title = models.CharField(max_length=200)
    logo_brand = models.ImageField(null=True, blank=True, upload_to='brand_logo/')

    class Meta:
        verbose_name = 'Product Brand'
        verbose_name_plural = 'Product Brands List'

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Product Category'
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.title


class ProductDetail(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE,
                                help_text='product that related to the current detail')
    price = models.FloatField(default=0, verbose_name='product price')
    discount_price = models.FloatField(verbose_name='product discount price',
                                       help_text='discount price for a product', null=True, blank=True)
    image = models.ImageField(verbose_name='product image', upload_to='products_image/', null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='product activation')
    quantity = models.IntegerField(verbose_name='product quantity', help_text='number of current product')
    color = models.CharField(max_length=100, verbose_name='product color')
    size = models.CharField(max_length=100, verbose_name='product size')

    class Meta:
        verbose_name = 'Product Details'
        verbose_name_plural = 'Product Details List'

    def __str__(self):
        return f'{self.price}'


class Product(models.Model):
    title = models.CharField(max_length=300, verbose_name='product title', db_index=True)
    main_image = models.ImageField(verbose_name='main image', help_text='main image of the current product', null=True,
                                   blank=True, upload_to='product_images_main/')
    short_description = models.CharField(max_length=500, verbose_name='product short description')
    description = models.TextField(verbose_name='product description')
    added_date = models.DateTimeField(auto_now_add=True, verbose_name='product added date')
    slug = models.SlugField(unique=True, db_index=True, null=False, default='', blank=True)
    category = models.ForeignKey(Category, verbose_name='product category',
                                 db_index=True, on_delete=models.CASCADE, null=True, blank=True)
    sell_count = models.IntegerField(default=0, null=True, blank=True, help_text='Number of product sales')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, db_index=True, null=True)
    visited_count = models.IntegerField(help_text='number of visited this product', default=0)
    is_delete = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    # objects = ProductManager()

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Product List'

    def get_absolute_url(self):
        return reverse('product_module:product-detail', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'


class ProductComment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=300)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'product comment'
        verbose_name_plural = 'product comment list'
        ordering = ['created_date']

    def __str__(self):
        return self.fullname


# save visited ip addresses
class Visited_Ip_product(models.Model):
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    user_ip = models.TextField(verbose_name='ip address', help_text='user ip address')

    def __str__(self):
        return self.user_ip

    class Meta:
        verbose_name = 'ip address'
        verbose_name_plural = 'users ip address'

product_module/forms.py
from django import forms
from .models import ProductComment


class CommentForm( forms.ModelForm ):
    class Meta:
        model = ProductComment
        fields = ('fullname', 'email', 'message', 'product')
        widgets = {
            'fullname': forms.TextInput( attrs={'class': 'form-control', 'type': "text"} ),
            'email': forms.TextInput( attrs={'class': 'form-control', 'type': "email"} ),
            'message': forms.Textarea(
                attrs={'class': 'form-control', 'rows': "7", 'id': "comment-text-input", 'cols': "80"} ),
            'product': forms.TextInput( attrs={'type': 'hidden'} )

        }

product_module/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.views.generic import ListView, DetailView
from .models import Product, ProductDetail, Category, Brand, ProductComment, Visited_Ip_product
from django.db.models import Min, Max, Q
from .forms import CommentForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.list import MultipleObjectMixin


class ProductListView(ListView):
    model = Product
    template_name = 'product_module/product_list_page.html'
    paginate_by = 9

    def get_queryset(self):
        print(self.request.GET)
        print(self.kwargs)
        print(self.request)

        products = Product.objects.filter(is_active=True, is_delete=False)
        brand = self.request.GET.getlist('brand')
        category = self.request.GET.getlist('category')
        order = self.request.GET.getlist('order')
        if brand:
            products = products.filter(brand__title__in=brand)

        if category:
            products = products.filter(category__title__in=category)

        # if order:
        #     if order == 'most-visit':
        #         products.order_by('visited_count')

        return products

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        marca_vals = set()
        marca_vals.update(self.request.GET.getlist('brand'))
        marca_vals.update(self.request.GET.getlist('category'))
        print(marca_vals)
        context['marca_vals'] = marca_vals
        context['title'] = 'product list'
        context['brands'] = Brand.objects.all()
        context['categories'] = Category.objects.all()
        return context


def get_json_filtering(request):
    print(request.GET)
    return JsonResponse({'response': 'response'})


# show products from newest to oldest
class NewProductListView(ListView):
    model = Product
    template_name = 'product_module/product_list_page.html'
    paginate_by = 2

    def get_queryset(self):
        products = Product.objects.all().order_by('-added_date')
        return products

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'new products'
        context['brands'] = Brand.objects.all()
        context['categories'] = Category.objects.all()
        return context


class ProductByBrand(ListView):
    model = Product
    template_name = 'product_module/product_list_page.html'
    paginate_by = 6
    ordering = ['id']

    def get_queryset(self, *, object_list=None, **kwargs):
        brand_name = self.kwargs.get('brand_name')
        products = Product.objects.filter(brand__title=brand_name).order_by('-added_date')
        brand = self.request.GET.getlist('brand')
        category = self.request.GET.getlist('category')
        if brand:
            products = products.filter(brand__title__in=brand)

        if category:
            products = products.filter(category__title__in=category)

        return products

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        marca_vals = set()
        marca_vals.update(self.request.GET.getlist('brand'))
        marca_vals.update(self.request.GET.getlist('category'))
        context['marca_vals'] = marca_vals
        context['title'] = 'products by brand'
        context['brands'] = Brand.objects.all()
        context['categories'] = Category.objects.all()
        return context


class ProductByCategory(ListView):
    model = Product
    template_name = 'product_module/product_list_page.html'
    paginate_by = 6
    ordering = ['id']

    def get_queryset(self, *, object_list=None, **kwargs):
        category_name = self.kwargs.get('category_name')
        return Product.objects.filter(category__title=category_name).order_by('-added_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'products by category'
        context['brands'] = Brand.objects.all()
        context['categories'] = Category.objects.all()
        return context


# get user ip
def get_ip(request):
    address = request.META.get('HTTP_X_FORWARDED_FOR')
    if address:
        ip = address.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


class ProductDetailView(DetailView, MultipleObjectMixin):
    model = Product
    template_name = 'product_module/product_detail_view_page.html'
    form_class = CommentForm
    paginate_by = 2

    def get_context_data(self, *args, **kwargs):
        object = self.object
        comments = ProductComment.objects.filter(product=object)
        context = super().get_context_data(object_list=comments, **kwargs)
        context['title'] = 'product detail'
        details = ProductDetail.objects.filter(product=object).all()
        # find min and max of prices
        min_max_price = details.aggregate(Min('price'), Max('price'))
        context['price__min'], context['price__max'] = min_max_price.values()
        comments = ProductComment.objects.filter(product=object)
        context['comment_form'] = self.form_class(initial={'product': self.object})
        related_products = [i for i in Product.objects.filter(brand=object.brand).order_by('?') if i != object]
        context['related_products'] = related_products
        paginator = Paginator(comments, 2)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj

        ip = get_ip(self.request)
        visited_ip_product = Visited_Ip_product.objects.filter(product=self.object, user_ip=ip).all()
        if len(visited_ip_product) == 0:
            Visited_Ip_product.objects.create(product=self.object, user_ip=ip)
            self.object.visited_count += 1
            self.object.save()

        return context

    def post(self, *args, **kwargs):
        comment_form = self.form_class(self.request.POST)
        if comment_form.is_valid():
            comment_form.save()
        return HttpResponseRedirect(self.request.path_info)


def get_product_detail(request):
    # print( 'request', request.GET )
    product_id = request.GET.get('product_id')
    detail_color = request.GET.get('color')
    product = Product.objects.filter(id=product_id).first()
    # product_detail = product.productdetail_set.filter( color=detail_color )
    product_detail = ProductDetail.objects.filter(product=product, color=detail_color).first()
    context = {'price': product_detail.price, 'discount_price': product_detail.discount_price,
               'quantity': product_detail.quantity}
    return JsonResponse(context)


def product_list_by_search(request):
    query = request.GET['q']
    context = {
        'title': 'search products'
    }
    if query is not None:
        lookup = Q(title__icontains=query) | \
                 Q(brand__title__icontains=query) | \
                 Q(category__title__icontains=query)
        search_products = Product.objects.filter(lookup).distinct()
        context['page_obj'] = search_products
        context['brands'] = Brand.objects.all()
        context['categories'] = Category.objects.all()
        return render(request, 'product_module/product_list_page.html', context)

product_module/templates/product_module/product_detail_view_page.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    <div id="content-wrapper">
        <div class="column">
            <img id=featured src="{{ object.main_image.url }}" style="width: 200px; height: 250px">
            <div id="slide-wrapper">
{#                <img id="slideLeft" class="arrow" src="{% static  'img/arrow-left.png' %}"#}
{#                     alt="{{ object.title }}">#}
                <div id="slider">
                    {% for detail in object.productdetail_set.all %}
                        {% if detail.image %}
                            <img class="thumbnail {% if forloop.counter == 1 %}active{% endif %}"
                                 src="{{ detail.image.url }}">
                        {% endif %}
                    {% endfor %}
                </div>
{#                <img id="slideRight" class="arrow" src="{% static 'img/arrow-right.png' %}">#}
            </div>
        </div>
        <div class="column">
            <h1 class="text-danger">{{ object.title|title }}</h1>
            <hr>
            <h5>
                <span class="text-primary">Category:</span> {{ object.category }} | <span
                    class="text-primary">Brand:</span>
                {{ object.brand.title }}
                <img id="logo-img" src="{{ object.brand.logo_brand.url }}">
            </h5>
            <hr>
            <h3>From ${{ price__min }} to ${{ price__max }}</h3>
            <form method="post" id="add-to-cart-form" action="{% url 'order_module:add-new-order' %}">
                {% csrf_token %}
                <div class="row m-1">
                    <input type="hidden" name="product" value="{{ object.id }}">
                    {% for detail in object.productdetail_set.all %}
                        <div class="radio-item mr-3">
                            <input type="radio" id="{{ detail.id }}" name="product-color" value="{{ detail.color }}"
                                   required="required">
                            <label for="{{ detail.id }}">{{ detail.color }}</label>
                        </div>
                    {% endfor %}
                </div>
                <div class="mt-3 mb-3" id="product-quantity"></div>
                <button class="btn btn-block btn-outline-success" type="submit" id="add-to-cart-btn">Add To Cart
                </button>
            </form>
        </div>
    </div>
    <hr>
    <!--product descriptions & comments & details -->
    <div class="container">
        <div class="row">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                       aria-controls="home" aria-selected="true">Description</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                       aria-controls="profile" aria-selected="false">Comments</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <p class="text-justify p-3 shadow mt-2">{{ object.description }}</p>
                </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <div class="row" id="comments">
                        <!--user comments-->
                        <div class="col-lg-5 col-md-5" id="user-comments">
                            {% for comment in page_obj %}
                                <div class="list-group">
								<span href="#" class="list-group-item">
									<h4 class="list-group-item-heading">{{ comment.fullname }}</h4>
									<hr class="bg-danger">
									<p class="list-group-item-text">
                                        {{ comment.message }}
                                        <br>
                                        <small class="text-secondary date">{{ comment.created_date|date:'M,d Y' }}</small>
                                    </p>
								</span>
                                </div>
                            {% endfor %}

                            <div class="col-md-6 offset-4 mt-1">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination">
                                        <li class="page-item">
                                            <a class="page-link" href="#" aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                            </a>
                                        </li>
                                        {% for page in paginator.page_range %}
                                            <li class="page-item"><a class="page-link"
                                                                     href="?page={{ page }}">{{ page }}</a>
                                            </li>
                                        {% endfor %}

                                        <li class="page-item">
                                            <a class="page-link" href="#" aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                            </a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <!--end user comments-->
                        <!--send comment-->
                        <div class="col-lg-7 col-md-7">
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputUsername">fullname: </label>
                                    {{ comment_form.fullname }}
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail">email: </label>
                                    {{ comment_form.email }}
                                </div>
                                <label>message : </label>
                                {{ comment_form.message }}
                                {{ comment_form.product }}
                                <button type="submit" class="btn btn-danger btn-block mt-1">send</button>
                            </form>
                        </div>
                        <!-- ends end comment-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end product descriptions & comments & details-->
    <hr>
    <div class="container">
        <div class="text-center">
            <h1><small>Related Products</small></h1>
            <div class="row">
                {% for related_product in related_products %}
                    {% include 'includes/product_detail_related_products_partial.html' with related_product=related_product %}
                {% endfor %}
            </div>

        </div>
    </div>
    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        console.log($.ajax)
        $('input[type="radio"]').change(function (event) {
            event.preventDefault();
            var content = $("input[name='product-color']:checked").val();
            var url = "{% url 'product_module:product-detail-price' %}";
            $.ajax({
                type: 'GET',
                dataType: 'json',
                url: url,
                data: {'product_id': {{ object.id }}, 'color': content},
                success: function (response) {
                    $("#product-quantity").trigger('reset'); //reset div
                    if (response.discount_price) {
                        temp = '<label for="quantity">' + 'Quantity:' + '</label><input class="form-control" type="number" id="quantity" name="quantity" min = "1" max ="' + response.quantity + '" required="required"> <br> <p> Price: <del> $' + response.price + ' </del> $' + response.discount_price + '(' + content + ') </p>'
                        $("#product-quantity").html(temp);
                    } else {
                        temp = '<label for="quantity">' + 'Quantity:' + '</label><input class="form-control" type="number" id="quantity" name="quantity" min = "1" max = "' + response.quantity + '" required="required"> <br> <p> Price: $' + response.price + '(' + content + ') </p>'
                        $("#product-quantity").html(temp);
                    }
                    if (response.quantity <= 0) {
                        $("#add-to-cart-btn").attr("disabled", true);
                        alert('product does not exist')
                    }
                },
                error: function (response) {
                    alert(response)
                }
            });
        });
        // radio button change
        //////////////////////////////////////////////////////////////
        let thumbnails = document.getElementsByClassName('thumbnail')
        let activeImages = document.getElementsByClassName('active')
        for (var i = 0; i < thumbnails.length; i++) {
            thumbnails[i].addEventListener('mouseover', function () {
                console.log(activeImages)
                if (activeImages.length > 0) {
                    activeImages[0].classList.remove('active')
                }
                this.classList.add('active')
                document.getElementById('featured').src = this.src
            })
        }
        let buttonRight = document.getElementById('slideRight');
        let buttonLeft = document.getElementById('slideLeft');
        buttonLeft.addEventListener('click', function () {
            document.getElementById('slider').scrollLeft -= 180
        })
        buttonRight.addEventListener('click', function () {
            document.getElementById('slider').scrollLeft += 180
        })
    </script>
{% endblock %}