E_commerce_application/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path( '', include( 'home_module.urls', namespace='home_module' ) ),
    path( 'products/', include( 'product_module.urls', namespace='product_module' ) ),
    path( 'order/', include( 'order_module.urls', namespace='order_module' ) ),
    path( 'accounts/', include( 'account_module.urls', namespace='account_module' ) ),
    path( 'contact-us/', include( 'contact_module.urls', namespace='contact_module' ) ),
    path( 'admin/', admin.site.urls ),
]

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

account_module/urls.py
from django.urls import path
from account_module import views

app_name = 'account_module'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('user-account/', views.UserAccountView.as_view(), name='user-account'),
    path('edit-account/', views.edit_user_info, name='edit-account'),
    path('active-account/<active_code>', views.activation_account_view, name='active_account'),
    path('forgot-password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password/<active_code>/', views.reset_password_view, name='reset_password'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

contact_module/urls.py
from django.urls import path
from . import views

app_name = 'contact_module'

urlpatterns = [
    path( '', views.ContactUsView.as_view(), name='contact-us' )
]

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home_module'

urlpatterns = [
    path( '', views.HomeView.as_view(), name='home-view' )
]

order_module/urls.py
from django.urls import path
from . import views

app_name = 'order_module'

urlpatterns = [
    path('add-user-order/', views.add_user_order, name='add-new-order'),
    path('add-coupon-code/', views.add_coupon_code, name='add-coupon-code'),
    path('user-orders/', views.user_orders_view, name='user-orders'),
    path('order-detail/<order_id>', views.user_order_detail, name='order-detail'),
    path('complete-order/', views.complete_order, name='complete-order'),
    path('user-open-order/', views.UserOpenOrder.as_view(), name='user-open-order'),
    path('change_item_counter', views.change_item_count, name='change_item_counter'),
    path('ajax/load-cities/', views.get_cities, name='load_cities'),
    path('export-pdf/<int:order_id>/', views.export_pdf_order, name='export-pdf-order')
]

product_module/urls.py
from django.urls import path
from . import views

app_name = 'product_module'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('new-products/', views.NewProductListView.as_view(), name='new-product-list'),
    path('product-brand/<brand_name>/', views.ProductByBrand.as_view(), name='product-list-by-brand'),
    path('product-category/<category_name>/', views.ProductByCategory.as_view(), name='product-list-by-category'),
    path('product-ajax-price/', views.get_product_detail, name='product-detail-price'),
    path('search/', views.product_list_by_search, name='search-products-list'),
    path('ajax_filtering/', views.get_json_filtering, name='ajax_filtering')
]

templates/shared/footer.html
<footer class="text-light bg-dark py-5">
    <div class="row p-5">
        <div class="col-6 col-md">
            <h5>Brand</h5>
            <ul class="list-unstyled text-small">
                {% for brand in brands %}
                    <li><a class="text-muted"
                           href="{% url 'product_module:product-list' %}?brand={{ brand.title }}">{{ brand.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Categories</h5>
            <ul class="list-unstyled text-small">
                {% for category in categories %}
                    <li><a class="text-muted"
                           href="{% url 'product_module:product-list' %}?category={{ category.title }}">{{ category.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Our Info</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted">{{ settings.phone }}</a></li>
                <li><a class="text-muted">{{ settings.email }}</a></li>
                <li><a class="text-muted">{{ settings.fax }}</a></li>
            </ul>
        </div>
{#        <div class="col-6 col-md">#}
{#            <h5>About</h5>#}
{#            <ul class="list-unstyled text-small">#}
{#                <li><a class="text-muted" href="#">Team</a></li>#}
{#                <li><a class="text-muted" href="#">Locations</a></li>#}
{#                <li><a class="text-muted" href="#">Privacy</a></li>#}
{#                <li><a class="text-muted" href="#">Terms</a></li>#}
{#            </ul>#}
{#        </div>#}
    </div>
</footer>

templates/shared/footer_references.html
{% load static %}
{#<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"#}
{#        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"#}
{#        crossorigin="anonymous"></script>#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous">
</script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="/static/js/custom.js"></script>

templates/shared/header.html
<nav class="navbar" id="main-title">
    <span class="mb-0">E-Commerce</span>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light mt-2">
    <a class="navbar-brand" href="{% url 'home_module:home-view' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                       data-toggle="dropdown" aria-expanded="false">
                        {{ request.user }} <i class="fa fa-user"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li>
                            <a class="dropdown-item"
                               href="{% url 'account_module:user-account' %}">
                                Your Account
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                               href="{% url 'order_module:user-open-order' %}">
                                Your Open Order
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item"
                               href="{% url 'account_module:logout' %}">Logout <i class="fa fa-sign-out"></i>
                            </a>
                        </li>
                    </ul>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_module:login' %}">Login <i class="fa fa-sign-in"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_module:register' %}">Register</a>
                </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                   data-toggle="dropdown" aria-expanded="false">
                    Brand
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                    {% for brand in brands %}
                        <li>
                            <a class="dropdown-item"
                               href="{% url 'product_module:product-list-by-brand' brand.title %}">
                                {{ brand.title }}
                            </a>
                        </li>
                    {% endfor %}
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'product_module:product-list' %}">All Products</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact_module:contact-us' %}">Contact Us</a>
            </li>
        </ul>
        {% include 'shared/search_product_component.html' %}
    </div>
</nav>

templates/shared/header_references.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rock+3D&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="shortcut icon" type="image/png" href="{% static 'admin/img/icon-yes.svg' %}"/>
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/shared/layout.html
{% load static %}
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'shared/header_references.html' %}
    <title>
        {% block title %}{% endblock %}
    </title>
</head>

<body>
{% render_partial 'home_module.views.header' %}

{% block content %}{% endblock %}
<!-- footer -->
<hr>
{% render_partial 'home_module.views.footer' %}
{% include 'shared/footer_references.html' %}
</body>

</html>

templates/shared/search_product_component.html
<form class="d-flex" method="get" action="{% url 'product_module:search-products-list' %}">
    <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search" name="q"
           value="{{ request.GET.q }}" required>
    <button class="btn btn-outline-success" type="submit">Search</button>
</form>